version: '2'

volumes:
  dbdata:

services:
  mysql:
    image: docker.io/bitnami/mariadb:10.6
    container_name: news-mysql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=newsmaker
      - MARIADB_DATABASE=news
    volumes:
      - "dbdata:/var/lib/mysql"
    ports:
      - 8006:3306

  laravel:
    image: docker.io/bitnami/laravel:9
    container_name: news-php
    ports:
      - '5173:5173'
      - '8000:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=newsmaker
      - DB_DATABASE=news
      - APP_TIMEZONE=Europe/Moscow
    volumes:
      - './:/app'
    depends_on:
      - mysql
